# Favicon
favicon: /favicon.ico

# SEO
keywords: ç”Ÿæ´»,åšå®¢,C++,Golang,C++,ç½‘ç»œç¼–ç¨‹,æ•°æ®åº?,åˆ†å¸ƒå¼?,å­˜å‚¨

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/dejavudwh
  # RSS: /atom.xml

# Nav menu
menu:
  home: /      
  archives: /archives
  categories and tags : /tags 
  about: /about  